Switch to using xcodebuild archive to build a signed binary.

diff --git a/build/makeDistribution b/build/makeDistribution
--- a/build/makeDistribution
+++ b/build/makeDistribution
@@ -32,7 +32,7 @@ if ! git diff-files --quiet --ignore-submodules
 then
   echo Outstanding changes exist.  Please check in all changes before building.
   git status --porcelain -uno
-  # exit 1
+  exit 1
 fi
 
 echo Disk Image name will be $DMG_NAME
@@ -61,15 +61,14 @@ pushd /tmp/switchlist-read-only/src
 # Rebuild help index.
 hiutil -C -a SwitchList.help -f SwitchList.help/SwitchList.help.helpindex
 
-xcodebuild -target SwitchList -configuration Release  clean
-# Build only for x86-64.
-xcodebuild ARCHS="x86_64" ONLY_ACTIVE_ARCH=NO  \
-           SYMROOT=/tmp/XcodeBuildProducts \
-           OBJROOT=/tmp/XcodeBuildIntermediates \
-           DSTROOT=/tmp/SwitchList.dst \
-           -configuration App\ Store \
-           -target SwitchList \
-           -target testAdvanceLayouts
+# Run all unit tests.
+xcodebuild -scheme SwitchList-release test
+if [ $? -ne 0 ]; then
+  echo "Unit tests failed."
+  exit 1
+fi
+
+xcodebuild -scheme SwitchList-release -archivePath /tmp/SwitchList.dst archive
 
 if [ $? -ne 0 ]; then
   echo Problems building SwitchList - problems during xcodebuild.
@@ -77,10 +76,7 @@ if [ $? -ne 0 ]; then
 fi
 popd 
 
-# Replace the new icon with the old so things work on 10.5.
-cp /tmp/switchlist-read-only/src/resources/icon-old.icns /tmp/SwitchList.dst/Applications/SwitchList.app/Contents/Resources/icon.icns
-
-cp -r /tmp/SwitchList.dst/Applications/SwitchList.app /tmp/SwitchList/
+cp -r /tmp/SwitchList.dst.xcarchive/Products/Applications/SwitchList.app /tmp/SwitchList/
 cp -r examples /tmp/SwitchList/Example\ Layouts
 cp -r template_examples /tmp/SwitchList/Custom\ Switchlist\ Examples
 
@@ -102,6 +98,6 @@ fi
 TestBinaryForFatness /tmp/Switchlist/SwitchList.app/Contents/MacOS/SwitchList "x86_64"
 
 # Test that layouts correctly advance without error.
-/tmp/XcodeBuildProducts/App\ Store/testAdvanceLayouts -m /tmp/XcodeBuildProducts/App\ Store/SwitchList.app/Contents/Resources/SwitchListDocument.momd/SwitchListDocument\ 7.mom examples/*/*.swl
+/tmp/SwitchList.dst.xcarchive/Products/usr/local/bin/testAdvanceLayouts -m /tmp/SwitchList.dst.xcarchive/Products/usr/local/bin/SwitchListDocument.momd/SwitchListDocument\ 7.mom examples/*/*.swl
 
 echo "/tmp/$DMG_NAME.dmg has the final disk image."
